SELECT L_SHIPMODE,
    SUM(
        CASE
            WHEN O_ORDERPRIORITY = '1-URGENT'
            OR O_ORDERPRIORITY = '2-HIGH' THEN 1
            ELSE 0
        END
    ) AS HIGH_LINE_COUNT,
    SUM(
        CASE
            WHEN O_ORDERPRIORITY <> '1-URGENT'
            AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
            ELSE 0
        END
    ) AS LOW_LINE_COUNT
FROM LINEITEM
    JOIN ORDERS ON L_ORDERKEY = O_ORDERKEY
WHERE L_SHIPMODE IN ('MAIL', 'SHIP')
    AND L_COMMITDATE < L_RECEIPTDATE
    AND L_SHIPDATE < L_COMMITDATE
    AND L_RECEIPTDATE >= DATE '1994-01-01'
    AND L_RECEIPTDATE < DATE '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;